import { Inter } from "next/font/google";
import Header from "./components/header/header";
import Footer from "./components/footer/footer";
import styles from "./global.module.scss"; 

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Samet Can Gözüaçık | Yazılım Geliştirici",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={styles.root}>
      <body className={inter.className}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
